In [1]:
import numpy as np

# karekök

In [2]:
np.sqrt(16)

4.0

In [3]:
sayı = -16
kk = np.sqrt(sayı)

repart = kk.real
impart = kk.imag

print(f"{sayı} sayısının karmaşık karekökü: {repart} + {impart}j")

-16 sayısının karmaşık karekökü: nan + 0.0j


C:\Users\cedgk\AppData\Local\Temp\ipykernel_33248\580933059.py:2: RuntimeWarning: invalid value encountered in sqrt
  kk = np.sqrt(sayı)


In [4]:
repart, impart

(nan, 0.0)

# kısa bir ara cmath modülü 

## karmaşık sayılarla çalışmak için hazırlanmış bir modüldür. 

In [5]:
import cmath

In [6]:
karekok = cmath.sqrt(sayı)
karekok


4j

In [7]:
z = complex(4,3)
z

(4+3j)

In [8]:
cmath.exp(z) # karmaşık sayının üssünü hespalar

(-54.051758861078156+7.704891372731154j)

In [9]:
cmath.log(z) # karmaşık sayının logaritmasını hespalar

(1.6094379124341003+0.6435011087932844j)

In [10]:
cmath.sin(z) 

(-7.61923172032141-6.5481200409110025j)

In [11]:
cmath.phase(z) # karmaşık sayının açısal değerini radyan cinsinden döndürür

0.6435011087932844

In [12]:
u = cmath.phase(z)
np.rad2deg(u)

36.86989764584402

In [13]:
cmath.polar(z) # karmaşık sayının normunu ve radyan cinsinden açısını döndürür. 

(5.0, 0.6435011087932844)

In [14]:
cmath.exp(1j * cmath.pi)

(-1+1.2246467991473532e-16j)

In [15]:
cmath.pi

3.141592653589793

## cmath over 
## numpy devam

# Trigonometrik Fonksiyonlar 

In [16]:
np.sin(0)

0.0

In [17]:
np.cos(0)

1.0

In [18]:
np.cos(90)

-0.4480736161291701

In [19]:
np.sin(np.deg2rad(90))

1.0

In [20]:
degree_value = 45
radian_value = np.deg2rad(degree_value)

print(f"{degree_value} derece = {radian_value:.4f} radyan")

45 derece = 0.7854 radyan


In [21]:
np.rad2deg(0.7854)

45.00010522957486

In [22]:
np.cos(40)**2 + np.sin(40) **2 

1.0

## ters trigonometrik fonksiyon

In [23]:
x = np.cos(np.deg2rad(45))
print(x)

0.7071067811865476


In [24]:
y = np.rad2deg(np.arccos(x))
y

45.0

In [25]:
np.rad2deg(np.arctan(1))

45.0

In [26]:
np.rad2deg(np.arctan(0))

0.0

# Euler sayısı 

In [27]:
euler_constant = np.e
print(f"Euler sayısı: {euler_constant: .15f}")

Euler sayısı:  2.718281828459045


In [28]:
euler_constant = np.exp(1)
print(f"Euler sayısı: {euler_constant: .15f}")

Euler sayısı:  2.718281828459045


In [29]:
np.exp(1)

2.718281828459045

# pi sayısı 

In [30]:
print(np.pi)

3.141592653589793


In [31]:
np.sin(np.pi/2)

1.0

In [32]:
pi_symbol = "\u03C0"
print(f"π sembolü: {pi_symbol}")


π sembolü: π


In [33]:
print(f"\u03C0 : {np.pi}")

π : 3.141592653589793


In [34]:
pi_approximation = np.pi
print(f"π sayısının yaklaşık değeri: {pi_approximation : .40f}")

π sayısının yaklaşık değeri:  3.1415926535897931159979634685441851615906


In [35]:
np.longdouble(np.pi)

3.141592653589793

# logoritma fonksiyonu 

## 10 tabanı için log10

In [36]:
np.log10(10)

1.0

##  ln - e tabanında logaritma için log kullanılır. 

In [37]:
np.log(np.e)

1.0

In [38]:
np.log(np.exp(2))

2.0

# Mutlak değer 

In [39]:
np.abs(-4)

4

In [40]:
np.absolute(-4)

4

In [41]:
y = 3.14
absolute_value_y = np.absolute(y)

print(f"{y} sayısının mutlak değeri: {absolute_value_y}")

3.14 sayısının mutlak değeri: 3.14


# yuvarlama işlemleri 

In [42]:
np.round(np.pi,16)

3.141592653589793

In [43]:
np.floor(np.pi) # aşağı yuvarlama

3.0

In [44]:
np.ceil(np.pi) # yukarı yuvarlama

4.0

In [45]:
np.trunc(9.81) # ondalıklı kısmı atarak yuvarlama

9.0

# numpy, Lineer Cebir ile iligidir asıl ! 

In [46]:
L = [1, 2, 3]
L

[1, 2, 3]

In [47]:
l1 = np.array(L) # listeyi numpy array'ine dönüştürür
l1

array([1, 2, 3])

In [48]:
l2 = np.array([-2, 1, -4])
l2

array([-2,  1, -4])

In [49]:
np.prod(l1) # dizi (array) elemanlarının çarpımı 

6

## inner (iç) product -- skaler çarpım

In [50]:
np.dot(l1, l2)

-12

In [51]:
l1 @ l2 # @ matris çarpma işlemi için kısaltmadır. 

-12

In [52]:
# İki matrisi tanımlayalım
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matris çarpımını hesaplayalım
C = A @ B
C

array([[19, 22],
       [43, 50]])

## iki vektör arasındaki açının hespalanması 

In [53]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

dot_product = vector1 @ vector2
norm_v1 = np.linalg.norm(vector1) # vektörün büyüklüğü 
norm_v2 = np.linalg.norm(vector2)

angle_radians = np.arccos(dot_product / (norm_v1 * norm_v2))
angle_degrees = np.degrees(angle_radians)

print("skaler çarpım sonucu = ", dot_product)
print(f"Açı (radyan): {angle_radians}")
print(f"Açı (derece): {angle_degrees}")

skaler çarpım sonucu =  32
Açı (radyan): 0.2257261285527342
Açı (derece): 12.933154491899135


In [54]:
def iki_vektör_açı(v1, v2):
    # Calculate the cross product of v1 and v2
    cross_product = np.cross(v1, v2)
    
    # Calculate the magnitudes (norms) of v1 and v2
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    
    # Calculate the sine of the angle
    sin_angle = np.linalg.norm(cross_product) / (norm_v1 * norm_v2)
    
    # Calculate the angle in radians
    angle_radians = np.arcsin(sin_angle)
    
    # Convert radians to degrees
    angle_degrees = np.degrees(angle_radians)
    
    return angle_radians, angle_degrees

In [55]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

angle_radians, angle_degrees = iki_vektör_açı(v1, v2)

print(f"Açı (radyan): {angle_radians}")
print(f"Açı (derece): {angle_degrees}")

Açı (radyan): 0.22572612855273394
Açı (derece): 12.93315449189912


## cross product --Vektörel çarpım 

In [56]:
np.cross(l1, l2)

array([-11,  -2,   5])

In [57]:
np.cross(vector1, vector2)

array([-3,  6, -3])

# Birim matris

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# .reshape()

In [60]:
arr =np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
a1 = arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# bazı array işlemleri

In [62]:
arr.max()

24

In [63]:
arr.min()

0

In [64]:
arr.sum()

300

In [65]:
arr.mean()

12.0

In [66]:
arr.argmax() # maximum eleman hangi indekste

24

In [67]:
arr.argmin() # minimum eleman hangi indekste

0

# Determinant 

In [68]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
np.linalg.det(a1)

0.0

In [70]:
np.linalg.inv(a1) # determinantı sıfır olduğundna singular

LinAlgError: Singular matrix

# çok boyutlu matrisler

In [71]:
arr =np.array([ -2,  1,  -2,  -3,  4,  5,  -6,  7,  8])

In [72]:
arr2 = arr.reshape(3,3)
arr2

array([[-2,  1, -2],
       [-3,  4,  5],
       [-6,  7,  8]])

In [73]:
np.linalg.det(arr2)

-5.999999999999997

## Matrisin tersi 

In [74]:
np.linalg.inv(arr2)

array([[ 0.5       ,  3.66666667, -2.16666667],
       [ 1.        ,  4.66666667, -2.66666667],
       [-0.5       , -1.33333333,  0.83333333]])

## arrayleri filtreleme

In [75]:
arr2

array([[-2,  1, -2],
       [-3,  4,  5],
       [-6,  7,  8]])

In [76]:
arr2 > 5

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [77]:
arr2 < 0

array([[ True, False,  True],
       [ True, False, False],
       [ True, False, False]])